### PR TITLE
Test for bugs in fix - to many

### PR DESCRIPTION
**Pull request by AndrewWyllie**
I believe a reverse form of the timing issue is now possible with this change - an update to the child table can be missed permanently if it arrives during caching. Added a test case to illustrate. I didn't have time to analyse how to fix it yet in detail but I think it may be sufficient just to move the CachedQuery object construction prior to the database retrieval. The other changes you made look like they should work well if we handle this case.

I tried for a while to repro a similar case for to-one but didn't manage to do it so far. I think because to-one always does single object retrievals from the cache (i.e. the 'find in memory' step of the deep fetch) it may not be possible for it to hit the same kind of issue. That said, I'd like to give it a bit more thought.

### CODE REVIEW

**Comment by mohrezaei** [comment]
I just ran these tests. The behavior is expected. The relationship is correctly resolved. It so happens that some of the objects in the relationship are out-of-date, but a resolved relationship will not re-query unless the actual items are incorrect. If the application needs higher consistency, the code should be run in a transaction (which will read-lock on the database).

The same thing happens in a much simpler situation: get a list of objects, then modify one of the objects inside via notification. The list will not re-resolve.

**Comment by AndrewWyllie** [comment]
I'm trying to make sure I'm reading your response very carefully but I think that's a different use case. Understood that a resolved list will not update. The issue this test is demonstrating is that the next findMany() and deepFetch() doesn't get the latest update either, which I believe is incorrect, and this only happens if the update coincides with the caching, i.e. it's another timing issue. The update here was 'lost' because associateSimplifiedResults() created a CachedQuery after the query had executed, so it captured update counters that are in the future relative to the query results. That update will never reflect in any subsequent new findMany/deepFetch, unless/until another update arrives to increment the update counter again, since that will invalidate the cache and cause the next findMany/deepFetch to retrieve from database. Let me know if you agree that's an issue, or else if I'm missing something.

I've started testing out a fix which just involves making associateSimplifiedResult() take the CachedQuery as a parameter, and then creating the CachedQuery at the beginning of the calling method instead (e.g. at the top of deepFetchToManyFromServer), before the list gets resolved. This ensures the CachedQuery captures the right update counts which I think should avoid any timing issue. I didn't complete the changes yet, partly because there's a lot of calling methods once we consider the usages of associateResultsWithAlternateMapper (which delegates to associateSimplifiedResult), but I tested enough to verify that it fixes the issue exposed by the test.

Actually to be precise what happens with the fix in place is the latest version of OrderItem 6 gets retrieved from the database by an 'extra' query when orderList2.getItems().size() executes (on line 325). However after some careful consideration I believe that's the correct/existing behaviour (not caused by the fix) based on my past analysis of the way deep fetch works.

Let me summarise my understanding so you can verify. Basically although deep fetch finds and caches the related objects up-front, when you call the related finder on the list to retrieve those objects, the related finder internally does a findMany() query, so it can actually go back to the database if it so happens that the deep fetch cached results got invalidated before the related finder got called. That's what happens in this test case once we apply the fix. Let me know if you agree or think I've misunderstood the existing behaviour. Although this behaviour doesn't seem the most efficient, and might be possible to optimise in future, I don't think it impacts correctness. Like you said, if someone wants to avoid the second database query they can wrap the code in a transaction.

If you agree with the above diagnosis and fix let me know and I can work on it later this week.

**Comment by mohrezaei** [comment]
I don't think I agree. Let me explain. 
This test `testDeepFetch_OneToMany_NotificationDuringChildCacheSimplifiedResult` fails. The log output with SQL enabled looks like:
```
2019-07-09 19:02:41,772 DEBUG [main] sqllogs.Order         - connection:319558327 find with: select t0.ORDER_ID,t0.ORDER_DATE,t0.USER_ID,t0.DESCRIPTION,t0.STATE,t0.TRACKING_ID from APP.ORDERS t0 where  t0.STATE = 'In-Progress'
2019-07-09 19:02:41,773 DEBUG [main] sqllogs.Order         - retrieved 4 objects, 2.0 ms per
2019-07-09 19:02:41,791 DEBUG [main] sqllogs.OrderItem     - connection:319558327 find with: select t0.ID,t0.ORDER_ID,t0.PRODUCT_ID,t0.QUANTITY,t0.ORIGINAL_PRICE,t0.DISCOUNT_PRICE,t0.STATE from APP.ORDER_ITEM t0 where  t0.ORDER_ID in ( 1,2,3,4)
2019-07-09 19:02:41,791 DEBUG [main] sqllogs.OrderItem     - retrieved 4 objects, 0.25 ms per
2019-07-09 19:02:41,791 INFO  [main] test.TestNotificationDuringDeepFetch     - associateSimplifiedResult starting wait
2019-07-09 19:02:41,791 INFO  [main] test.TestNotificationDuringDeepFetch     - associateSimplifiedResult done waiting
2019-07-09 19:02:41,810 INFO  [main] test.TestNotificationDuringDeepFetch     - update APP.ORDERS set STATE = 'In-Progress' where ORDER_ID = 55
2019-07-09 19:02:41,811 INFO  [main] test.TestNotificationDuringDeepFetch     - update APP.ORDER_ITEM set STATE = 'Something Else' where ID = 6 and ORDER_ID = 55
2019-07-09 19:02:41,811 INFO  [main] test.TestNotificationDuringDeepFetch     - Performing deep fetch retrieval with concurrent database update and notification
2019-07-09 19:02:41,811 INFO  [Thread-7] test.TestNotificationDuringDeepFetch     - update thread starting wait
2019-07-09 19:02:41,811 DEBUG [main] sqllogs.Order         - connection:319558327 find with: select t0.ORDER_ID,t0.ORDER_DATE,t0.USER_ID,t0.DESCRIPTION,t0.STATE,t0.TRACKING_ID from APP.ORDERS t0 where  t0.STATE = 'In-Progress'
2019-07-09 19:02:41,812 DEBUG [main] sqllogs.Order         - retrieved 5 objects, 0.2 ms per
2019-07-09 19:02:41,812 DEBUG [main] sqllogs.OrderItem     - connection:319558327 find with: select t0.ID,t0.ORDER_ID,t0.PRODUCT_ID,t0.QUANTITY,t0.ORIGINAL_PRICE,t0.DISCOUNT_PRICE,t0.STATE from APP.ORDER_ITEM t0 where  t0.ORDER_ID in ( 1,2,3,4,55)
2019-07-09 19:02:41,813 DEBUG [main] sqllogs.OrderItem     - retrieved 6 objects, 0.16666666666666666 ms per
2019-07-09 19:02:41,813 INFO  [main] test.TestNotificationDuringDeepFetch     - associateSimplifiedResult starting wait
2019-07-09 19:02:41,813 INFO  [Thread-7] test.TestNotificationDuringDeepFetch     - update thread done waiting
2019-07-09 19:02:41,813 INFO  [Thread-7] test.TestNotificationDuringDeepFetch     - update APP.ORDER_ITEM set STATE = 'In-Progress' where ID = 6 and ORDER_ID = 55
2019-07-09 19:02:41,813 INFO  [Thread-7] test.TestNotificationDuringDeepFetch     - update thread done updating
2019-07-09 19:02:41,813 INFO  [main] test.TestNotificationDuringDeepFetch     - associateSimplifiedResult done waiting
2019-07-09 19:02:41,814 INFO  [main] test.TestNotificationDuringDeepFetch     - Performing final deep fetch retrieval
```
The update performed by `Thread-7` is firing after everything has been read from the database for that list (the top level orders and their items) -- it's not even happening during anything. Furthermore, the update is such that while it affects the dirtiness of the items retrieved for the list, it does not change the relationships.  Any order in that list returns the correct order items (one of which is dirty).

The test fails on 
```java
        Assert.assertEquals(6, orderList3.getItems().asEcList().count(orderItemStateEqualsInProgress));
```
which is not a verification of relationships/deep fetch.

Does that help explain the situation?

**Comment by AndrewWyllie** [comment]
Thanks for the quick response!

Ok let's take this in two parts.

1)
>> The update performed by Thread-7 is firing after everything has been read from the database for that list 

That's correct, but it's happening before the result of the database read has been cached by associateSimplifiedResult. The caching is on hold until the update thread has signalled that it is done. This is the harnessed method below. When control returns from the update thread, it calls super.associateSimplifiedResult() which creates a new CachedQuery. This CachedQuery contains the update counter of the update made by the update thread, but the result it is caching pre-dates that update:

```
        @Override
        protected void associateSimplifiedResult(Operation op, List resultList, CachedQuery baseQuery)
        {
            if (timingTestCase == TimingTestCase.WAIT_DURING_CHILD_CACHE_SIMPLIFIED_RESULT)
            {
                signalAndWaitForUpdate("associateSimplifiedResult");
            }
            super.associateSimplifiedResult(op, resultList, baseQuery);
        }
```

2) With regard to dirtiness of the results, would you expect that the results should be eventually consistent if we do another new deep fetch and there's no other updates coming in? That's what happens already. You can easily demonstrate that without making any other code changes, just by swapping the order of the if-block and the super call in the test harness above. You will see that the assert returns 6 OrderItems matching the 'In-Progress' state, which reflects the update done by the update thread, even though that update happened after the  deep fetch result was cached. That's because the query result cache gets invalidated even with today's behaviour.

i.e.
```
        @Override
        protected void associateSimplifiedResult(Operation op, List resultList, CachedQuery baseQuery)
        {
            // Swapped the order
            super.associateSimplifiedResult(op, resultList, baseQuery);
            if (timingTestCase == TimingTestCase.WAIT_DURING_CHILD_CACHE_SIMPLIFIED_RESULT)
            {
                signalAndWaitForUpdate("associateSimplifiedResult");
            }
        }
```
This is the resulting test failure on line 328 - which fails because it receives more results than I originally expected (for the reasons I attempted to explain in the last paragraph of my previous response):
```
java.lang.AssertionError: 
Expected :5
Actual   :6
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.gs.fw.common.mithra.test.TestNotificationDuringDeepFetch.runDeepFetchOneToManyTest_NotificationDuringChildCacheSimplifiedResult(TestNotificationDuringDeepFetch.java:328)
	at com.gs.fw.common.mithra.test.TestNotificationDuringDeepFetch.testDeepFetch_OneToMany_NotificationDuringChildCacheSimplifiedResult(TestNotificationDuringDeepFetch.java:243)
```

Let me know what you think.

**Comment by mohrezaei** [comment]
> This CachedQuery contains the update counter of the update made by the update thread

Huh? It better not. The update thread is touching `ORDER_ITEM.STATE`, which is nowhere in the original query or the deep fetches.

(Also, I didn't quite understand what you meant by 2., but we should resolve 1. first)

**Comment by AndrewWyllie** [comment]
Ok so the first thing to verify is that my test is accurately simulating an update notification on a partial cached object.

My assumption is that notification will call PartialCacheMithraNotificationListener.onUpdate method. That's what the test simulates.

```
    public void onUpdate(MithraDataObject[] mithraDataObjects, Attribute[] updatedAttributes, Object sourceAttributeValue)
    {
        this.onUpdateForPartialCache(mithraDataObjects, updatedAttributes, sourceAttributeValue);
    }
```
In turn, onUpdateForPartialCache method marks the impacted objects as dirty (if they were in the cache) and updates the update counter if any object was marked dirty:
```
        if (updatedAttributes == null || dirtyCount > 0)
        {
            getMithraObjectPortal().incrementClassUpdateCount();
        }
```
So the update to OrderItem 6 should result in the update counter for OrderItem class getting incremented I believe.

I would expect the orderList.items() related finder operation should be depending on the OrderItem update counter (and the test seems to bear this out). Is this a fair assumption? Can use the debugger to make sure if needed.

**Comment by mohrezaei** [comment]
ok, I understand the issue now. Will take a look in a few days.

**Comment by AndrewWyllie** [comment]
Cool, thanks Moh. Let me know if you want any help.

I'll also try to find time to review the other files in your change that I didn't get to yet, although I doubt I'm going to find any other problems.

**Comment by AndrewWyllie** [comment]
I think the same type of timing issue will also exist in cacheResults() which creates a CachedQuery for each individual related object key / foreign key. I would expect if we try to traverse the relationship from an individual parent object (e.g. Order) then it may return a stale related object list (e.g. OrderItem). I dealt with this case in the original pull request by creating a map of CachedQuery objects corresponding to opToListMap, at the same time as we create the opToListMap, before the queries are executed. We could merge in that part of my changes and it should fix it, unless you think we should take a different approach?

I will also see if I can devise a test case to demonstrate. Will submit it if I succeed.

**Comment by mohrezaei** [comment]
Fixed the two test cases. Keep'em coming :smile:

**Comment by AndrewWyllie** [comment]
Nice fix.

I only found one other issue but also added a bunch of test cases for everything that I tested. Raised a separate pull request for that to bring it onto your branch:
https://github.com/mohrezaei/reladomo/pull/2

I think that should be the last of it from what I can see.

**Pull request merged**
